### ISSUE TITLE
Referenced variable before assignment in AnimusHTTPLog.py

### ISSUE THREAD

**Issue by klustic** [Animus-Intelligence/omni#2]
Issue is here: [AnimusHttpLog.py:148](https://github.com/Animus-Intelligence/omni/blob/master/animus/LogParsers/AnimusHttpLog.py#L148)

Suggest adding `continue` within except clause

Traceback:
```
Traceback (most recent call last):
  File "./omni-reduce", line 421, in <module>
    main()
  File "./omni-reduce", line 85, in main
    logfile = AnimusHttpLog(lines, config['API_KEY'], config['BASE_URI'])
  File "/home/user/omni/animus/LogParsers/AnimusHttpLog.py", line 44, in __init__
    self._getFeatures(logfile)
  File "/home/user/omni/animus/LogParsers/AnimusHttpLog.py", line 148, in _getFeatures
    if 'datetime' in parsedLine:
UnboundLocalError: local variable 'parsedLine' referenced before assignment
```

**Comment by luciddr34m3r** [comment]
This exception is thrown when the log format is vhost_combined.

LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined

**Comment by luciddr34m3r** [comment]
Port after the host ip is mucking up the regex.
